### ISSUE TITLE
why disable msvc?

### ISSUE THREAD

**Issue by felixf4xu** [hughsie/libxmlb#175]
Hi,

I'm trying to build this project in Windows, with MSVC, but the code disabled it.

https://github.com/hughsie/libxmlb/blob/4393955fb7c8bbcb6a2c65ff54f16c39dc165e59/meson.build#L89-L91

I checked the code and found that ` __attribute__((cleanup))` is not used in the source code, so why disable `msvc`?

**Comment by ximion** [comment]
> I checked the code and found that ` __attribute__((cleanup))` is not used in the source code, so why disable `msvc`?

It is, any `g_auto`/`g_autoptr` macro makes use of it. Ideally build with gcc or clang instead, MSVC is a huge nightmare to work with with projects like this.

**Comment by brunvonlope** [comment]
@hughsie There is some reason to use such g_auto/g_autoptr macros and turn impossible to build on a platform on purpose?

Right now, it is impossible to build libxmlb and appstream on windows with vcpkg due to that

**Comment by hughsie** [comment]
> Right now, it is impossible to build libxmlb and appstream on windows with vcpkg due to that

Don't use vcpkg, it's just not good enough.

**Comment by brunvonlope** [comment]
"Don't use libxmlb, its memory management it's just not good enough"

Well, the project is yours so you are free to ignore C standard and use fancy extensions to make your work easier in detriment of others, but ignoring a direct question is sad to say the least

**Comment by hughsie** [comment]
> There is some reason to use such g_auto/g_autoptr macros

Okay, I'll answer the _direct question_: **Because I want to**. There are ~500 places in the code where it's convenient (or more efficient) to use `__attribute__((cleanup(...)))`.

**Comment by ximion** [comment]
Not having this kind of RAII in C produces far less readable and maintainable code, not only is there not a lot of benefit to switching away from it, given that `clang-cl` exists, doing so would also truly make the code a lot less maintainable and any attempt at conversion would most definitely cause some kind of memory management bugs by accident.

MSVC is pretty bad at C support because MS cares a lot more about C++ anyway (it has recently improved, but GCC/Clang still reign supreme). To have a good experience on Windows, using `clang-cl` is actually an excellent, MSVC-compatible option. And if you are using some nice environment like MSYS2 (which builds native Windows binaries), then you'll have a much better time anyway.
