### ISSUE TITLE
xb_string_search() is UTF8 unfriendly

### ISSUE THREAD

**Issue by hughsie** [hughsie/libxmlb#77]
This is tricky to fix as xb_string_search is in the fast path and we don't want to allocate memory.

**Comment by pwithnall** [comment]
Prompted by [this gnome-software bug](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1011). In particular, libxmlb uses `strncmp()` for comparing human-readable strings, when it should probably actually be casefolding, normalising, and dropping accents then using `strcmp()`. It’s fine for libxmlb to use `strcmp()` for comparing machine-readable strings.

One solution that Richard suggested is to do the casefolding/normalising/accent-dropping at silo build time, for all strings, thus keeping query time fast. An optimisation which could be made here is that most English strings won’t actually change when they’re casefolded/normalised/accent-dropped, so the silo doesn’t need to store two copies of the string in that case. Since English is unfortunately what’s in most XML files that libxmlb touches, we might as well take advantage of it.

**Comment by hughsie** [comment]
@pwithnall do you know if there a Glib function for dropping accents?

**Comment by pwithnall** [comment]
See `g_str_match_string()` and the tokenise-and-fold functions

**Comment by hughsie** [comment]
I think b72caf961f7b07059fe0e574efee26786e5905db properly fixed this.
